FROM python:3.10

# Prevent interactive dialogs from halting the build
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y \
    build-essential \
    libcairo2-dev \
    libhdf5-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./pip/mchip_requirements.txt ./pip/mchip_requirements.txt
RUN pip install -U pip && \
    pip install -v --no-cache-dir \
    --trusted-host pypi.python.org \
    --trusted-host files.pythonhosted.org \
    --trusted-host pypi.org \
    --trusted-host data.dgl.ai \
    --trusted-host download.pytorch.org \
    -r ./pip/mchip_requirements.txt

COPY ./pip/mchip_dev_requirements.txt ./pip/mchip_dev_requirements.txt
RUN pip install -U pip && \
    pip install -v --no-cache-dir \
    --trusted-host pypi.python.org \
    --trusted-host files.pythonhosted.org \
    --trusted-host pypi.org \
    --trusted-host data.dgl.ai \
    --trusted-host download.pytorch.org \
    -r ./pip/mchip_dev_requirements.txt

COPY setup.py .
COPY VERSION .
COPY build.sh .
COPY ./atomsci atomsci/

# Install atomsci-ampl
RUN ./build.sh
RUN pip install -e .

# Clean up
RUN apt-get purge -y build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
RUN rm -rf /root/.cache/pip
