FROM python:3.10-slim

RUN pip install uv
WORKDIR /app

COPY pyproject.toml .
COPY atomsci ./atomsci
COPY VERSION .

RUN uv sync --extra cpu

CMD ["uv", "run", "python", "-c", "import atomsci; print('cpu ok')"]
