FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3.10 python3-pip
RUN python3.10 -m pip install uv

WORKDIR /app
COPY pyproject.toml .
COPY atomsci ./atomsci
COPY VERSION .

RUN uv sync --extra cuda

CMD ["uv", "run", "python3.10", "-c", "import atomsci; print('cuda ok')"]
