
[project]
name = "ampl"
version = "1.0"

# NOTE:
# * deepchem only works with python <= 3.10 (and possibly 3.11)
#   - seems to install in python 3.11 but website says suports only 
#     python <= 3.10
#   - does not work with python 3.12+ due to tensorflow-addons dependency
#     which is no longer supported and only has support up to python 3.11
# * ampl only works with python 3.9, 3.10, 3.11 (due to deepchem)
#   - encoders / decoders need python 3.9
#   - everthing else works with python 3.9 and 3.10 (and possibly 3.11)
# * this will install on python 3.12 but won't have deepchem
requires-python = ">=3.9,<3.13"

# Dependencies for all Python versions
dependencies = [
    "setuptools",
    "pip",

    # core dependencies
    "torch_cluster",
    "torch_scatter",
    "torch_sparse",
    "torch_spline_conv",
    "torch-geometric",

    # deepchem 2.8.0 deps [NOTE: may not work on python >= 3.11]
    "deepchem[torch,tensorflow]==2.8.0; python_version >= '3.10' and python_version < '3.12'",

    # deepchem[tensorflow] deps
    "tensorflow-cpu==2.14.0; python_version >= '3.10' and python_version < '3.12'",

    # atomsci-ampl deps [need to be added to atomsci-ampl]
    "molvs",
    "xgboost",
    "umap-learn",
    "imbalanced-learn",
    "ipykernel",
    "ipython",
    "pytest",
    "seaborn",
    "matplotcheck",

    # code repos
    "atomsci-ampl; python_version >= '3.10' and python_version < '3.12'",
    "atomsci-clients",

    # rdkit
    "rdkit>=2024.3.5; python_version >= '3.10'",

    "numpy<2",

    # python specific versions [dgl / pyg dependent]
    "dgl==2.1.0; python_version >= '3.10'",

    "pyg_lib==0.3.1; python_version >= '3.10' and python_version < '3.12'",
    "pyg_lib==0.4.0; python_version >= '3.12'",

    "torch==2.1.2+cpu; python_version >= '3.10' and python_version < '3.12'",
    "torch==2.3.1+cpu; python_version >= '3.12'"
]


[tool.uv]
allow-insecure-host = [
    "download.pytorch.org",
    "data.dgl.ai",
    "data.pyg.org"
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu/torch_stable.html"
format = "flat"

[[tool.uv.index]]
name = "dgl"
url = "https://data.dgl.ai/wheels/repo.html"
format = "flat"

[[tool.uv.index]]
# NOTE: pyg libraries for torch >= 2.2 seem to have GLIBC incompatibilities on LC
name = "pyg_lib_py312"
url = "https://data.pyg.org/whl/torch-2.3.1+cpu.html"
format = "flat"

[[tool.uv.index]]
name = "pyg_lib_py310"
url = "https://data.pyg.org/whl/torch-2.1.2+cpu.html"
format = "flat"

[tool.uv.sources]
# code repos
atomsci-ampl = [
    { git = "https://github.com/ATOMScience-org/AMPL.git", rev = "py310",  marker = "python_version >= '3.10'"}
]
atomsci-clients = { git = "ssh://git@czgitlab.llnl.gov:7999/atom/clients.git", rev = "master" }

# dgl
dgl = { index = "dgl" }

# torch
torch = { index = "pytorch" }
pyg_lib = [
    { index = "pyg_lib_py310", marker = "python_version >= '3.10' and python_version < '3.12'" },
    { index = "pyg_lib_py312", marker = "python_version >= '3.12'" },
]
torch_cluster = [
    { index = "pyg_lib_py310", marker = "python_version >= '3.10' and python_version < '3.12'" },
    { index = "pyg_lib_py312", marker = "python_version >= '3.12'" },
]
torch_scatter = [
    { index = "pyg_lib_py310", marker = "python_version >= '3.10' and python_version < '3.12'" },
    { index = "pyg_lib_py312", marker = "python_version >= '3.12'" },
]
torch_sparse = [
    { index = "pyg_lib_py310", marker = "python_version >= '3.10' and python_version < '3.12'" },
    { index = "pyg_lib_py312", marker = "python_version >= '3.12'" },
]
torch_spline_conv = [
    { index = "pyg_lib_py310", marker = "python_version >= '3.10' and python_version < '3.12'" },
    { index = "pyg_lib_py312", marker = "python_version >= '3.12'" },
]

