name: "APT Reset"

on: [push]

jobs:
  show-apt-sources:
    runs-on: ubuntu-24.04
    steps:
      - name: Show image version
        run: |
          cat /etc/microsoft-prod-release || echo "File not found"
          dpkg -l | grep microsoft
          dpkg -l | grep mssql
          dpkg -l | grep azure
      - name: Show apt sources
        run: |
          echo "=== /etc/apt/sources.list ==="
          cat /etc/apt/sources.list
          echo "=== /etc/apt/sources.list.d/ ==="
          ls -l /etc/apt/sources.list.d/
          for f in /etc/apt/sources.list.d/*.list; do
            echo "=== $f ==="
            cat "$f"
          done
  reset-apt:
    runs-on: ubuntu-latest
    steps:
      - name: Reset apt sources
        run: |
          # your cleanup commands here
          sudo rm -f /etc/apt/sources.list.d/*
          sudo apt-get clean
          sudo apt-get update