# How to run manually:
# 1. Go to the GitHub repository.
# 2. Click the "Actions" tab.
# 3. Select this workflow, "docker publish".
# 4. Click "Run workflow".
# 5. Choose the desired inputs, then click "Run workflow".

name: docker publish

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Deployment environment"
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - staging
      target:
        description: "Which image(s) to build"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - gpu
          - rocm
          - cpu-amd64
          - cpu-arm64

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Uses Dockerfile.gpu
          - name: gpu
            platform: gpu
            arch: ""
          # Uses Dockerfile.rocm
          - name: rocm
            platform: rocm
            arch: ""
          # Uses Dockerfile.cpu
          - name: cpu-amd64
            platform: cpu
            arch: ""
          # Uses Dockerfile.arm
          - name: cpu-arm64
            platform: arm
            arch: linux/arm64

    if: |
      github.event.inputs.target == 'all' ||
      github.event.inputs.target == matrix.name

    steps:
      - name: Set up QEMU
        if: ${{ matrix.arch == 'linux/arm64' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and push Docker image
        run: |
          make push-docker
        env:
          ENV: prod
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
